lab2/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab2/Models/FormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class FormModel
    {
        [Display(Name = "Imie")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Data")]
        public DateTime Description { get; set; }
      
    }
}

lab2/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FormModel model)
        {
            if (ModelState.IsValid)
            {
                return View("Created", model);
            }
            return View(model);
        }
    }
}

lab2/Controllers/HomeController.cs
using WebApplication1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

       
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab2/Views/Form/Create.cshtml
@model lab2_test.Models.FormModel
@{
    ViewData["Title"] = "Form-Create";
}

<h1 class="display-4">Formularz</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Form" asp-action="Create" method="post">

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

lab2/Views/Form/Created.cshtml
@model WebApplication1.Models.FormModel
@{
    ViewData["Title"] = "Form-Created";

}

<div class="text-left">
    <h1 class="display-4">Data</h1>
    @Html.DisplayNameFor(model => model.Name):          @Html.DisplayFor(model => model.Name)


<p>
    od wybranej daty do teraz upłyneło:
    @{
        TimeSpan roznica = DateTime.Now - Model.Description;
    }
    @roznica.Days
    dni.
  
</p>

</div>

lab2/Views/Form/Index.cshtml
@{
    ViewData["Title"] = "Form-Index";
}

<h1>@ViewData["Title"]</h1>

<p>Implicit Razor expression - Current date: @DateTime.Now !</p>

<p>Explicit Razor expression - Last week this time: @(DateTime.Now - TimeSpan.FromDays(7))</p>

@{
    void RenderName(string name)
    {
        <p>Name: <strong>@name</strong></p>
    }

    RenderName("Mahatma Gandhi");
    RenderName("Martin Luther King, Jr.");
}

lab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home-Index";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <p>Parametr p1 = @ViewData["p1"]</p>
</div>

lab2/Views/Home/Test2.cshtml
@{
    ViewData["Title"] = "Home-";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <p>id = @ViewData["id"]</p>
    <p>param2 = @ViewData["p2"]</p>
    <p>param3 = @ViewData["p3"]</p>
    <p>param4 = @ViewData["p4"]</p>

</div>

lab2/Views/Home/Test3.cshtml
@{
    ViewData["Title"] = "Home-";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    
</div>

lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab2_test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Form" asp-action="Create">Form-Create</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                      
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - lab2_test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>